name: "Run Tests"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"
  push:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"

jobs:
  treewide-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        package: [nix-bindings-sys]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - name: Run tests for ${{ matrix.package }}
        run: |
          eval "$(nix print-dev-env)"
          set -x

          cargo test -p ${{ matrix.package }} | exit 1
